version: '3.3'

networks:
  network-grafana:
    driver: bridge

services:
    
    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        networks:
            - network-grafana
            
        restart: always
        ports:
            - '3000:3000'
        environment: 
            - GF_INSTALL_PLUGINS=grafana-googlesheets-datasource
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=PasswordOfChoice
        volumes: 
            - ./var/lib/grafana/:/var/lib/grafana